language: java
jdk:
  - openjdk8
services:
  - docker
script:
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mv ./target/travisci-0.0.1-SNAPSHOT.jar ./
  - bash pushdocker.sh
