language: java
jdk:
  - openjdk8
services:
  - docker
script:
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mv ./target/travisci-0.0.1-SNAPSHOT.jar ./
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t travis .
  - docker push zhipengma/travisci:travis
