server:
  port: 8000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-2zel09ln911339663wo.mysql.rds.aliyuncs.com:3306/user?useUnicode=true&characterEncoding=utf8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: kI3ivbc3vkytQZBU
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
